# Generated by Django 4.0.2 on 2022-04-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
    ]
